### ISSUE TITLE
AttributeError: 'Source' object has no attribute 'compilation_database' 

### ISSUE THREAD

**Issue by tex** [zchee/deoplete-clang#10]
[deoplete] Traceback (most recent call last):                                                                                                                                   
[deoplete]   File "/home/milan/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 57, in completion_begin                                                    
[deoplete]     complete_position, candidates = self.gather_candidates(context)                                                                                                  
[deoplete]   File "/home/milan/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 93, in gather_candidates                                                   
[deoplete]     results = self.gather_results(context)                                                                                                                           
[deoplete]   File "/home/milan/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 168, in gather_results                                                     
[deoplete]     context['candidates'] = source.gather_candidates(context)                                                                                                        
[deoplete]   File "/home/milan/.vim/bundle/deoplete-clang/rplugin/python3/deoplete/sources/deoplete_clang.py", line 38, in gather_candidates                                    
[deoplete]     if self.compilation_database:                                                                                                                                    
[deoplete] AttributeError: 'Source' object has no attribute 'compilation_database'                                                                                              
[deoplete] An error has occurred. Please execute :messages command.

**Comment by Shougo** [comment]
Please upload minimal init.vim less than 50 lines and reproduce ways from neovim starting.

**Comment by zchee** [comment]
@tex @Shougo Maybe this problem caused by this https://github.com/zchee/deoplete-clang/issues/11.
