### ISSUE TITLE
g:deoplete#sources#clang#clang_complete_database

### ISSUE THREAD

**Issue by tex** [zchee/deoplete-clang#11]
Can you describe g:deoplete#sources#clang#clang_complete_database in detail?
From current doc I'm not able to understand where it should point to.

Thanks!

**Comment by zchee** [comment]
@tex Hi!
I'll reply later :)

**Comment by zchee** [comment]
@tex Sorry for late reply :(

**Currently**, meaning of the `g:deoplete#sources#clang#clang_complete_database` is the directory in which the presence of `compile_commands.json`.
The reason it is not a json file path, because API of python binding of clang was its implementation.

e.g. In `neovim/neovim`, `compile_commands.json` is exists `/path/to/neovim_clone_dir/build`.
In that case,
```vim
let g:deoplete#sources#clang#clang_complete_database = /path/to/neovim_clone_dir/build
```

but, I feel that hard it is to understand a directory path of rather than a json file path :(
Maybe **I change this setting value to json file path** someday.

BTW, I planned automatically search `compile_commands.json` behavior. such as YouCompleteMe.
Also, I would like to fully compatible support `.ycm_extra_conf`.


Does that make sense?

**Comment by tex** [comment]
It is clear that this variable shall point to folder. It is not clear why neovim sources are needed.
Neovim sources are needed to use this plugin, correct?
I have ArchLinux with neovim package, do I need to clone neovim to get that compile_command.json?

**Comment by zchee** [comment]
@tex No, no! Not needs clone neovim repository :)
I will post detailed example with sample `compile_commands.json`.
Also, I will briefly describe the operation of deoplete-clang.

**Comment by zchee** [comment]
@tex Tentative, Here is actually outputed the json https://github.com/zchee/.nvim/tree/master/compile_commands

**Comment by tex** [comment]
Archlinux:
pacaur -Ql neovim |grep compile_commands.json
Nothing found

I cloned neovim source, build it, pointed clang_complete_database to build folder there and it worked.

**Comment by tex** [comment]
So where to get compile_command.json - is this file needed or is it created by your plugin so we only need an existing folder where your plugin stores these files?

**Comment by zchee** [comment]
@tex Now I'm writing a description of the easy-to-understand `compile_commands.json`.
Wait a moment please :)

**Comment by tex** [comment]
Ohh, I understand that now. The compile_command.json contains information about how to compile each source file. Only files with information about how to compile them specified in this file will show up in completion.
Correct?

**Comment by tex** [comment]
Fully support of .ycm_extra_conf would be great. Without it, it is always a question how to get appropriate json file for project I'm working on.

**Comment by tex** [comment]
Also, is there any mapping between project name and name of json file? Or all json files from specified folder are loaded / parsed by this plugin?

**Comment by zchee** [comment]
@tex Correct!
deoplete-clang also clang-python3 is fake(?) build and parse each languages AST.
And returns the corresponding to your input context.
But, If exists `compile_commands.json` in `g:deoplete#sources#clang#clang_complete_database` directory, Parse it, and it gives priority to the build command information.

However, Is optional to provide to clang even if you had a `compile_commands.json`.
Maybe not perfect for the context (build result), but completion feature will work.

> Also, is there any mapping between project name and name of json file? Or all json files from specified folder are loaded / parsed by this plugin?

Maybe It has been decided that the name of `compile_commands.json`, So it will be selected from the build directory structure.
Current behavior, deoplete-clang (clang-python3) will only search `compile_commands.json` in directory.
- http://clang.llvm.org/docs/JSONCompilationDatabase.html

If you want to output the `compile_commands.json` with the build, e.g. `cmake`, Please add `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON` in the flag of cmake.
- https://cmake.org/pipermail/cmake/2013-December/056517.html

**Comment by zchee** [comment]
@tex Also I'm consider get json by project (root directory) name.
e.g. In neovim, `neovim.json`.
