### ISSUE TITLE
autocompletion automatically inserts (wrong) text - reposted

### ISSUE THREAD

**Issue by lewicki-pk** [zchee/deoplete-clang#12]
Hello, I'm reposting this issue from Shougo/deoplete.
Can you please take a look?

# Problems summary
When I'm writing my C++ code autocompletion automatically inserts first value from the list.

## Expected
I would like to just see the autocompletion list and disable option responsible for inserting actual characters from autocompletion menu.

## Environment Information

 * OS: Ubuntu 15.10
 * Neovim version: NVIM 0.1.3-dev

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
call plug#begin('~/.nvim/plugged')

Plug 'scrooloose/nerdtree'
Plug 'Shougo/deoplete.nvim'
Plug 'zchee/deoplete-clang'
Plug 'Shougo/neoinclude.vim'
Plug 'benekastah/neomake'
Plug 'bling/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'jistr/vim-nerdtree-tabs'
Plug 'majutsushi/tagbar'
Plug 'dantler/vim-alternate'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'szw/vim-tags'

call plug#end()

let g:deoplete#enable_at_startup = 1

set completeopt-=preview

let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-3.6/lib/libclang.so.1'
let g:deoplete#sources#clang#clang_header = '/usr/lib/clang'
let g:deoplete#sources#clang#std#c = 'c11'
let g:deoplete#sources#clang#std#cpp = 'c++1z'
let g:deoplete#sources#clang#sort_algo = 'priority'

```

## The reproduce ways from neovim starting (Required!)

Currently I cannot think of a simple way to reproduce this. I came across this during following tutorial for cppCMS library (but I hope it's some minor issue or option that I simply don't know).

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Screen shot (if possible)
https://www.youtube.com/watch?v=AaHg1IZ4890&feature=youtu.be

## Upload the log file
[log.zip](https://github.com/zchee/deoplete-clang/files/165482/log.zip)

**Comment by zchee** [comment]
@lewicki-pk Thanks re-post :)

At first, I was worried about whether this settings are correct.
`let g:deoplete#sources#clang#clang_header = '/usr/lib/clang'`

Could you tell me this commands result?
```bash
$ ls -la /usr/lib/clang
$ ls -la /usr/lib/llvm-3.6/lib
```

**Comment by zchee** [comment]
@lewicki-pk Ah, I was mistaken for other issue :(
I post the correct answer later.

**Comment by lewicki-pk** [comment]
@zchee Thanks. It's not that urgent but sometimes it's really annoying.

Just in case I'm uploading the result of:
$ tree -a /usr/lib/llvm-3.6/lib /usr/lib/clang
[tree.txt](https://github.com/zchee/deoplete-clang/files/166865/tree.txt)

**Comment by zchee** [comment]
@lewicki-pk Sorry again for kate reply :(
I will reply absolutely today.

**Comment by zchee** [comment]
@lewicki-pk Hi!
I checked your post youtube. I understand the problem and came up with a cause.
Do you use `set completeopt+=preview`? It seems to you use preview.

There is a possibility that has been fixed, but previously `deoplete.nvim` did not recommend `preview`.
(Maybe related to Neovim core behavior, I do not grasp all.)

**Comment by Shougo** [comment]
@zchee 
Hm.   The preview window feature conflicts the auto completion?
If so, deoplete must disable the feature.

**Comment by Shougo** [comment]
@lewicki-pk Your minimal init.vim is not minimal.
Please test the real minimal init.vim without the plugin manager.
The real minimal init.vim is like below.

```vim
set rtp+=~/work/deoplete.nvim
set rtp+=~/work/deoplete-clang

let g:deoplete#enable_at_startup = 1

set completeopt-=preview

let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-3.6/lib/libclang.so.1'
let g:deoplete#sources#clang#clang_header = '/usr/lib/clang'
let g:deoplete#sources#clang#std#c = 'c11'
let g:deoplete#sources#clang#std#cpp = 'c++1z'
let g:deoplete#sources#clang#sort_algo = 'priority'
```

**Comment by lewicki-pk** [comment]
@Shougo 
I have reproduced this problem with deoplete-clang disabled as you can see in the init.vim below:

```vim
" Plugins
call plug#begin('~/.nvim/plugged')

" On demand loading
Plug 'Shougo/deoplete.nvim'
"Plug 'zchee/deoplete-clang' << disabled

call plug#end()

set completeopt-=preview

let g:deoplete#enable_at_startup = 1
```

Even though I have `set completeopt-=preview` explicitly in my init.vim- after executing `:verbose set completeopt` I still have:

completeopt=longest,menuone,preview
        Last set from ~/.nvim/plugged/deoplete.nvim/autoload/deoplete/handlers.vim

I'm not sure where but I think that I saw something similar in your old issues..
Should I move this once more to deplete issues?

**Comment by lewicki-pk** [comment]
Probably it's not related to completeopt-> preview, because I opened nvim, reproduced the issue and than executed `set completeopt-=preview` and with `completeopt=longest,menuone` I still was able to reproduce the issue..

**Comment by lewicki-pk** [comment]
I have added `let g:deoplete#_saved_completeopt = "menuone,noinsert"` to init.vim but the problem still occurs and some plugin still inserts completion (which is even more strange now that I have added "noinsert" option)..

**Comment by zchee** [comment]
@lewicki-pk Hmm...
Just in case, Could you try to check git log if you use not latest `deoplete.nvim`.

**Comment by Shougo** [comment]
It seems deoplete-clang problem.
