### ISSUE TITLE
deoplete-clang disabling other deoplete sources

### ISSUE THREAD

**Issue by SageEx** [zchee/deoplete-clang#15]
When ``deoplete-clang`` is enabled, deoplete does not show completion from other sources like buffers or ultisnips.
This has been checked for 2-3 cpp files - all completions are from clang source( which is quite slow). There is not a single member of other sources. (``deoplete-clang`` config on the left part of the split)

Without ``deoplete-clang``
![2016-03-23-10 26 05](https://cloud.githubusercontent.com/assets/7141867/13976132/b0d7071a-f0e2-11e5-8873-cb882ee4678c.png)

With ``deoplete-clang``
![2016-03-23-10 25 46](https://cloud.githubusercontent.com/assets/7141867/13976142/c48e6ff0-f0e2-11e5-897d-384eb23fa7f9.png)

**Comment by zchee** [comment]
@SageEx Thanks create a issue :)
I'll debug later.

**Comment by zchee** [comment]
@SageEx BTW, 

```vim
let g:deoplete#enable_refresh_always = 1
```
Maybe, solved this problem with this setting.
Can you can try it?

**Comment by SageEx** [comment]
@zchee No, this solution does not work.

This is just a guess but probably you are setting ``deoplete-clang`` as the
only source and not appending it to the deoplete sources.
I am only guessing, please ignore if not true.

Thanks.

On Wed, Mar 23, 2016 at 11:41 AM, Koichi Shiraishi <notifications@github.com

**Comment by zchee** [comment]
@SageEx Sorry, I do not understand all :(
Which code line? or in my init.vim...?

Anyway, I want to reproduce in the same environment as you.
Could you post the reproducible tiny `init.vim`?
I want only `deoplete.nvim` and `deoplete-clang` in `&runtimepath`.

**Comment by SageEx** [comment]
@zchee I was only guessing, I did not look at the code. Anyway, here is the minimal init.vim
```vim
call plug#begin("~/.config/nvim/plugged")

    Plug 'Shougo/deoplete.nvim' | Plug 'Shougo/neopairs.vim'
        let g:deoplete#enable_at_startup = 1
        let g:deoplete#enable_smart_case = 1
        inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
        inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<TAB>"
        inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
        inoremap <expr><BS> deoplete#mappings#smart_close_popup()."\<C-h>"
        let g:deoplete#omni_patterns = {}
        let g:deoplete#auto_completion_start_length = 1
        let g:deoplete#sources = {}
        let g:deoplete#sources._ = []
        let g:neopairs#enable = 1
        let g:deoplete#file#enable_buffer_path = 1
    Plug 'zchee/deoplete-clang', { 'for': 'cpp' }
        let g:deoplete#sources#clang#libclang_path = '/usr/lib/libclang.so'
        let g:deoplete#sources#clang#std#cpp = 'c++14'
        let g:deoplete#sources#clang#clang_header = '/usr/lib/clang'

        Plug 'sirver/ultisnips'
        let g:UltiSnipsJumpForwardTrigger="<c-j>"
        let g:UltiSnipsExpandTrigger="<c-j>"
        let g:UltiSnipsEditSplit="vertical"
        let g:UltiSnipsListSnippets="<c-e>"
        Plug 'honza/vim-snippets'

call plug#end()


filetype plugin indent on
syntax on

function! s:my_cr_function() abort
    return pumvisible() ? deoplete#mappings#close_popup() : "\<CR>"
endfunction
```
Without ``deoplete-clang``
![2016-03-23-12 56 13](https://cloud.githubusercontent.com/assets/7141867/13978410/d3bd4c1c-f0f6-11e5-8ed9-bed55266fb1a.png)

With ``deoplete-clang``
![2016-03-23-12 55 29](https://cloud.githubusercontent.com/assets/7141867/13978426/e5fe312a-f0f6-11e5-959b-7d23ef9601e2.png)

See how without ``deoplete-clang`` there are two completions, one from buffer, another from ultisnips.
With ``deoplete-clang`` only clang sources are present.

**Comment by zchee** [comment]
@SageEx Hmm..
I did a simple test. but will work :(

BTW, Can you post the files in that image?

**Comment by SageEx** [comment]
@zchee  That is strange, for me it does not work.. :cry: 
If you had completion from other sources, then it will probably work on this file too. The file is a simple template file. 
```c++
#include<bits/stdc++.h>
using namespace std;
#define maX(a,b)                     ( (a) > (b) ? (a) : (b))
#define miN(a,b)                     ( (a) < (b) ? (a) : (b))
#define mp make_pair // useful for working with pairs
#define fi first
#define se second
typedef long long ll;
typedef long long int lli;
typedef vector<long> vl;
typedef vector<ll> vll;
typedef vector<string> vs;
typedef vector<vl > vvl;
typedef pair<long,long> lp;
#define sz(a) int((a).size())
#define pb push_back
#define all(c) (c).begin(),(c).end()
#define tr(c,i) for(auto i = (c).begin(); i != (c).end(); i++)
#define cpresent(c,x) (find(all(c),x) != (c).end())
#define present(c,x) ((c).find(x) != (c).end())
#define rep(i,a,b) for(auto i = (a); i<(b);i++)
#define repd(i,a,b) for(auto i = (a);i>=(b);i--)
#define dbg(vari) cerr<<#vari<<" = "<<(vari)<<"  ";
#define mn cout<<"\n";

int main(){
    ios_base::sync_with_stdio(false);cin.tie(NULL);

    int longvariable = 0;
    int anotherlongvariable = 0;

    
    

    return 0;
}

```

Another test, if you type typedef, is there any completion from the buffer source ?

**Comment by zchee** [comment]
@SageEx 

### === not work section ===

Just in case, UtilSnip have not `retu` snip.
So, Your post

![](https://cloud.githubusercontent.com/assets/7141867/13978426/e5fe312a-f0f6-11e5-959b-7d23ef9601e2.png)

is natural that it will not be displayed it is OK?

Next, `UtilSnip` has not `get_complete_position` and `self.self.input_pattern`.
So `ret` after `backspace <BS>`, It does not support.
e.g.

```cpp
    retu|

    return 0;
}

// type <BS>

    ret|

    return 0;
}
```

ss
![screenshot 2016-03-24 18 13 44](https://cloud.githubusercontent.com/assets/6366270/14012901/544ae42a-f1ec-11e5-96e7-11f13b584138.png)

![screenshot 2016-03-24 18 13 56](https://cloud.githubusercontent.com/assets/6366270/14012912/6a0eb94e-f1ec-11e5-9b0f-ca9887be2a4f.png)

### === work section ===

but, continue to `<BS>` -> `t`, It will work.

![screenshot 2016-03-24 18 14 03](https://cloud.githubusercontent.com/assets/6366270/14012914/6eb18ca6-f1ec-11e5-8975-aac2e2e68e60.png)

Also, I try `r` -> `re`, will work.

![screenshot 2016-03-24 18 09 21](https://cloud.githubusercontent.com/assets/6366270/14012822/bd072510-f1eb-11e5-8064-6602fdf4eb0e.png)

I use this, something similar with your vimrc without vim-plug.

```vim
" Tiny init.vim for deoplete-clang
set runtimepath+=$HOME/src/github.com/Shougo/deoplete.nvim
set runtimepath+=$HOME/src/github.com/zchee/deoplete-clang
set runtimepath+=$HOME/.cache/nvim/dein/repos/github.com/sirver/ultisnips
set runtimepath+=$HOME/.cache/nvim/dein/repos/github.com/honza/vim-snippets

let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_smart_case = 1
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<TAB>"
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
inoremap <expr><BS> deoplete#mappings#smart_close_popup()."\<C-h>"
let g:deoplete#omni_patterns = {}
let g:deoplete#auto_completion_start_length = 1
let g:deoplete#sources = {}
let g:deoplete#sources._ = []
let g:neopairs#enable = 1
let g:deoplete#file#enable_buffer_path = 1

let g:deoplete#sources#clang#libclang_path = "/opt/llvm/lib/libclang.dylib"
let g:deoplete#sources#clang#clang_header = '/opt/llvm/lib/clang'
" clang default include flags
"   - echo | clang -v -E -x c -
let g:deoplete#sources#clang#flags = [
      \ "-cc1",
      \ "-triple", "x86_64-apple-macosx10.11.0",
      \ "-emit-obj",
      \ "-mrelax-all",
      \ "-disable-free",
      \ "-disable-llvm-verifier",
      \ "-mrelocation-model", "pic",
      \ "-pic-level", "2",
      \ "-mthread-model", "posix",
      \ "-mdisable-fp-elim",
      \ "-munwind-tables",
      \ "-target-cpu", "core2",
      \ "-target-linker-version", "264.3",
      \ "-dwarf-column-info",
      \ "-debugger-tuning=lldb",
      \ "-resource-dir", "/opt/llvm/lib/clang/3.9.0",
      \ "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk",
      \ "-ferror-limit", "19",
      \ "-fmessage-length", "213",
      \ "-stack-protector", "1",
      \ "-fblocks",
      \ "-fobjc-runtime=macosx-10.11.0",
      \ "-fencode-extended-block-signature",
      \ "-fmax-type-align=16",
      \ ]
let g:deoplete#sources#clang#sort_algo = 'priority'

let g:UltiSnipsJumpForwardTrigger="<c-j>"
let g:UltiSnipsExpandTrigger="<c-j>"
let g:UltiSnipsEditSplit="vertical"
let g:UltiSnipsListSnippets="<c-e>"

filetype plugin indent on
syntax on

function! s:my_cr_function() abort
    return pumvisible() ? deoplete#mappings#close_popup() : "\<CR>"
endfunction
```

I do not know yet is why you do not work... :(

**Comment by zchee** [comment]
@SageEx and, I posted init.vim is already you test it with fix each `path` only.
maybe c flags is not need. remove it.
Please fix romtimepath and libclang path.

Please retry really tiny init.vim! 🙏

**Comment by SageEx** [comment]
@zchee Thanks for the detailed expanation. 
Indeed I was backspacing to see the ultisnips snippets and as you told it did not work.
I tried other snippets like `if` and they worked but they were at the end of the completion list. When I used 
```vim
call deoplete#custom#set('buffer', 'rank', 9999)
call deoplete#custom#set('ultisnips', 'rank', 9999)
```
they showed up just fine in the completion list and all is well again.

Thanks a lot :bow: .

**Comment by zchee** [comment]
@SageEx np!
I was relieved to hear it :)
