### ISSUE TITLE
C struct member omnicomplete

### ISSUE THREAD

**Issue by theirnwlf** [zchee/deoplete-clang#18]
## Problems summary
I'm working with kernel source code. Tested and using deoplete and neoinclude which turned out to be simply amazing for my c code. Exactly what i was looking for - autocomplete across included headers, works just great! Only thing I'm trying to get now is omnicomplete for structure/union members. From what I've seen, people get amazing autocomplete suggestions using deoplete. Sadly I have faild to get it to work so far. While <C-x><C-o> gives accurate candidates(but takes a lot of time), combination of deoplete + neoinclude + deoplete-clang fails here.

## Expected
struct/union members only candidate suggestion with deoplete

## Environment Information

 - OS: Ubuntu 14.04
 - Neovim version: 0.1.3-dev

## minimal init.vim
```vim
call plug#begin('~/.vim/plugged')

Plug 'Shougo/deoplete.nvim'

Plug 'Shougo/neoinclude.vim'

Plug 'zchee/deoplete-clang'

call plug#end()

let g:deoplete#enable_at_startup = 1

set path=~/dev/modules/linux/include/
set tags=./tags;/

let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-3.4/lib/libclang.so'
let g:deoplete#sources#clang#clang_header = '/usr/lib/llvm-3.4/lib/clang'

let g:deoplete#omni_input_patterns = {}
let g:deoplete#omni_input_patterns.c = '[^.[:digit:] *\t]\%(\.\|->\)\w*'
let g:deoplete#omni_input_patterns.cpp = '[^.[:digit:] *\t]\%(\.\|->\)\w*\|\h\w*::\w*'
```

## The reproduce ways from neovim starting (Required!)

So in this test i have kernel path set do kernel include dir `~/dev/modules/linux/include/` and test.c file in `~/dev/modules`.  For test added /foobar/foobar.h to linux include dir. The results I get are shown in screenshot.

> #ifndef FOOBAR_H
> #define FOOBAR_H
> 
> typedef struct foobar_s
> {
> 	int foofoo;
> 	foobar_s *next;
> 	int barbar;
> }foobar_t;
> 
> #endif

## Screen shot 

![screenshot from 2016-03-27 20_54_40](https://cloud.githubusercontent.com/assets/18103980/14067564/6cda26fe-f467-11e5-88fa-d6a013254808.png)

![screenshot from 2016-03-27 20_56_51](https://cloud.githubusercontent.com/assets/18103980/14067565/709985b4-f467-11e5-93de-00d23179e528.png)

**Comment by zchee** [comment]
@cirnwlf Thanks.

 > I'm working with kernel source code.

I'm surprised. Thanks for using deoplete-clang :)

I will debug.
Please wait a little.

**Comment by zchee** [comment]
@cirnwlf This issue caused by `deoplete-clang` does not parse `path` dir.
I will fix the behavior.

**Comment by zchee** [comment]
@cirnwlf Sorry, I misunderstand.

If surrounded by a `main(){}`, It will works.

![screenshot 2016-03-31 12 05 26](https://cloud.githubusercontent.com/assets/6366270/14166366/d30dff66-f74d-11e5-9cd8-b7937c815500.png)

Maybe, `libclang` will return context aware completion words.
`deoplete-clang` does not touch this behavior.

also, YCM will same behavior :(

WDTY?

**Comment by cirnwlf** [comment]
Ok, so I have been using my nvim setup for two days now on my computer at work and overall it was working perfectly. On different computer (the one I was initially testing deoplete-clang on) it doesn't work.
I will investigate and let You know.

Great job with your plugins, thanks :)

**Comment by Shougo** [comment]
Please re-open the issue if you reproduce the issue.
I will test it.
