### ISSUE TITLE
Request to improve: recommend using locate to determine path to libclang.so on Linux

### ISSUE THREAD

**Issue by paulherman** [zchee/deoplete-clang#21]
Is there any particular reason for not using "locate libclang.so" instead of "find ..."? I believe that there are some cases in which this fails, specifically libclang is not in $PATH, but then the "find ..." can be used as a fallback. This is due to the long time that find takes to process all the entries.

**Comment by Shougo** [comment]
I cannot find my libclang.so by `locate` command.
I don't think it is not useful.

```
% locate libclang.so
[1]    6698 exit 1     locate libclang.so
% find /usr/lib -name libclang.so
/usr/lib/llvm-3.8/lib/libclang.so
```
