### ISSUE TITLE
Makes deoplete not work because of libclang.so.3.7

### ISSUE THREAD

**Issue by degva** [zchee/deoplete-clang#23]
## The problem
Deoplete stops working and keeps sending the error below not even I enter to INSERT mode.
Maybe because the clang version (?)

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/degva/.config/nvim/plugged/deoplete-clang/rplugin/python3/deoplete/clang/clang/cindex.py", line 3652, in register_function                                        
[deoplete]     func = getattr(lib, item[0])      
[deoplete]   File "/usr/lib/python3.5/ctypes/__init__.py", line 360, in __getattr__
[deoplete]     func = self.__getitem__(name)                              
[deoplete]   File "/usr/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__
[deoplete]     func = self._FuncPtr((name_or_ordinal, self))                  
[deoplete] AttributeError: /usr/lib/libclang.so.3.7: undefined symbol: clang_CXXField_isMutable
[deoplete]                                                    
[deoplete] During handling of the above exception, another exception occurred:
[deoplete]                                          
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/degva/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 47, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)        
[deoplete]   File "/home/degva/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 79, in gather_candidates
[deoplete]     self.load_sources()                                 
[deoplete]   File "/home/degva/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 258, in load_sources
[deoplete]     source = module.Source(self.__vim)
[deoplete]   File "/home/degva/.config/nvim/plugged/deoplete-clang/rplugin/python3/deoplete/sources/deoplete_clang.py", line 64, in __init__
[deoplete]     self.index = clang.Index.create()
[deoplete]   File "/home/degva/.config/nvim/plugged/deoplete-clang/rplugin/python3/deoplete/clang/clang/cindex.py", line 2357, in create
[deoplete]     return Index(conf.lib.clang_createIndex(excludeDecls, 0))
[deoplete]   File "/home/degva/.config/nvim/plugged/deoplete-clang/rplugin/python3/deoplete/clang/clang/cindex.py", line 141, in __get__        
[deoplete]     value = self.wrapped(instance)
[deoplete]   File "/home/degva/.config/nvim/plugged/deoplete-clang/rplugin/python3/deoplete/clang/clang/cindex.py", line 3733, in lib
[deoplete]     register_functions(lib, not Config.compatibility_check)
[deoplete]   File "/home/degva/.config/nvim/plugged/deoplete-clang/rplugin/python3/deoplete/clang/clang/cindex.py", line 3680, in register_functions
[deoplete]     register (function)
[deoplete]   File "/home/degva/.config/nvim/plugged/deoplete-clang/rplugin/python3/deoplete/clang/clang/cindex.py", line 3677, in register
[deoplete]     return register_function(lib, item, ignore_errors)
[deoplete]   File "/home/degva/.config/nvim/plugged/deoplete-clang/rplugin/python3/deoplete/clang/clang/cindex.py", line 3658, in register_function
[deoplete]     raise LibclangError(msg)                            
[deoplete] clang.cindex.LibclangError: /usr/lib/libclang.so.3.7: undefined symbol: clang_CXXField_isMutable. Please ensure that your python bindings are compatible with your libclang.so version. 
[deoplete] An error has occurred. Please execute :messages command.
```

## Expected
Deoplete should work even I'm not working with any kind of c file.

## Environment Information

 - OS: ArchLinux 4.4.5-1
 - Neovim version: v0.1.4-23-gf47a20a

## Provide a minimal init.vim with less than 50 lines and not plugin manager (Required!)

```vim
call plug#being() 

" deoplete
Plug 'Shougo/deoplete.vim'
Plug 'zchee/deoplete-clang'

call plug#end()

let g:deoplete#sources#clang#libclang_path = "/usr/lib/libclang.so"
let g:deoplete#sources#clang#clang_header = "/usr/lib/clang"
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)
Not sure what should I put here. I start neovim via the command line, executing `nvim`.

## Generate a logfile if appropriate
Following the steps shown:
[log-nvim_22875.txt](https://github.com/zchee/deoplete-clang/files/219060/log-nvim_22875.txt)

## Upload the log file
[nvimlog.txt](https://github.com/zchee/deoplete-clang/files/219072/nvimlog.txt)

Thanks!

**Comment by zchee** [comment]
@degva Ok, I'll check it on Docker container.

**Comment by degva** [comment]
@zchee I've installed the latest version of llvm+clang, and I've put these variables:

```vimrc
let g:deoplete#sources#clang#libclang_path = "/opt/llvm/lib/libclang.so.3.8"
let g:deoplete#sources#clang#clang_header = "/opt/llvm/lib/clang"
```

yet I'm receving the same error of `AttributeError: /usr/lib/libclang.so.3.7`. So I'm assuming those variables are not working? deoplete is not using the correct libraries?

Thanks!

**Comment by rsw0x** [comment]
Removing lines 3067-3069 and 1184-1188 of [this](https://github.com/zchee/libclang-python3/blob/master/clang/cindex.py) file fixes it for me as a temporary workaround. Not sure if this is a newly added symbol or a symbol that was removed.

**Comment by degva** [comment]
@rsw0x Well, I didn't want to modify that file at all.
BUT, problem is solved now.

My system was using clang 3.7.1 which comes from the "extra" repositories. Installing clang from aur - which name is "clang-svn" - compiles the version 3.9.0.

After it, deoplete-clang works as expected.

**Comment by timlag1305** [comment]
I am having the same issue as noted above.  The OS I am using is FreeBSD 10.3 with Clang 3.8.1 which I install through the official repositories.
The relevant nvim.init configuration is:
`let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_complete_start_length = 1
let g:deoplete#sources#clang#libclang_path = '/usr/local/llvm38/lib/libclang.so'
let g:deoplete#sources#clang#clang_header = '/usr/local/llvm38/include/clang/'
let g:deoplete#sources#clang#std#c = 'c11'
let g:deoplete#sources#clang#std#cpp = 'c++14'
let g:deoplete#sources#clang#sort_algo = 'priority'`

The fix offered by @rsw0x works.

**Comment by Toqozz** [comment]
I have the same issue.

**Comment by zchee** [comment]
@degva @rsw0x @timlag1305 @Toqozz Sorry for late reply :(

Now, I'm in the hospital. Discharge from hospital the tomorrow or day after tomorrow.

===

understand all.
I'm using `clang 3.9 svn latest`, so do not occur error.
`libclang-python3` is following the latest, but many Linux distribution does not provide 3.9.
I think self-compile is cumbersome, I will consider to something countermeasures.
But additional the code for this problem is bad idea, will use git tag, branch or etc.

**Comment by degva** [comment]
@zchee Hope you are alright

----
Yes, @Toqozz install clang from aur repo. It's called "clang-svn". It downloads the source, the 3.9 version, and it will compile it automatically for you, so you wont need to compile it by yourself.

**Comment by Toqozz** [comment]
@zchee I also hope that you are alright.

@degva right now I'm just using @rsw0x's solution, I don't want to have 3 versions of clang!

**Comment by sQu1rr** [comment]
clang 3.9 is unstable in most repos (e.g. gentoo - even 3.8 is marked unstable), can you please fix this issue or make isMutable optional or something?

**Comment by BeTmAsTeR** [comment]
I have the same problem as above

Complete error message:
`error caught in async handler 'deoplete_on_buffer [{b'event': b'BufEnter', b'max_abbr_width': 138, b'complete_str': b'', b'input': b'    printf("ciao")', b'position': [0, 5, 19, 0], b'ignorecase': 1, b'camelcase': 0, b'sources
': [], b'smartcase': 1, b'changedtick': 28, b'filetype': b'c', b'delay': 0, b'next_input': b';    ', b'filetypes': [b'c'], b'max_menu_width': 138, b'keyword_patterns': b'[a-zA-Z_][a-zA-Z@0-9_\xc3\x80-\xc3\xbf]*'}]':
LibclangError('/usr/lib/libclang.so.3.7: undefined symbol: clang_CXXField_isMutable. Please ensure that your python bindings are compatible with your libclang.so version.',)
Traceback (most recent call last):
  File "/home/betmaster/.config/nvim/plugged/deoplete-clang/rplugin/python3/deoplete/clang/clang/cindex.py", line 3652, in register_function
    func = getattr(lib, item[0])
  File "/usr/lib/python3.5/ctypes/__init__.py", line 360, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libclang.so.3.7: undefined symbol: clang_CXXField_isMutable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/neovim/plugin/host.py", line 91, in _on_notification
    handler(*args)
  File "/usr/lib/python3.5/site-packages/neovim/plugin/host.py", line 160, in decoder
    return fn(*walk(decode_if_bytes, args, decode))
  File "/home/betmaster/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 42, in on_buffer
    self.__deoplete.on_buffer(context)
  File "/home/betmaster/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 346, in on_buffer
    self.check_recache()
  File "/home/betmaster/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 341, in check_recache
    self.load_sources()
clang.cindex.LibclangError: /usr/lib/libclang.so.3.7: undefined symbol: clang_CXXField_isMutable. Please ensure that your python bindings are compatible with your libclang.so version.
`
