### ISSUE TITLE
The completion windows pop up when it should not show.

### ISSUE THREAD

**Issue by zhou13** [zchee/deoplete-clang#28]
## Problems summary

The completion windows pop up when it should not show.

Case:
````
#include <iostream>

using namespace std;

class Foo {
public:
    void work();
};

int main()
{
    Foo x; 
    x.work(); |
}
````
If you put the cursor after `|` and go into insert mode, a completion window will pop up.  This is not expected.

My vim configuration:
````
" deoplete
let g:deoplete#enable_at_startup = 1
let g:deoplete#sources#clang#libclang_path = "/usr/lib/libclang.so"
let g:deoplete#sources#clang#clang_header = "/usr/lib/clang"
let g:neopairs#enable = 1
````

**Comment by zchee** [comment]
@zhou Thanks!
Maybe it's problem is caused by `self.input_pattern` (not tested)
I will check and fix later. please a moment.

**Comment by zchee** [comment]
@zhou Sorry, It questions.

At first, I have never written a C(C++) \o/
and For example, Golang have this `if` idiom.

```go
if err := foo(); err != nil {
	return err
}
```

Is C also have it?
If so, I think that operation is normal. What about you think?

**Comment by zchee** [comment]
@zhou Oh, misunderstood 😱
**not show**? If so, it's bug.

I do not yet test, will test later.

**Comment by zhou13** [comment]
I think the completion window should NOT pop up in this situation since it is after a statement ending with `;`.  It should follow my setting in `g:deoplete#auto_complete_start_length`.

**Comment by zhou13** [comment]
OK.  I think this is a deoplete bug.  I will make a pull request there.
