### ISSUE TITLE
request: implement Goto like YCM

### ISSUE THREAD

**Issue by butterflyfish** [zchee/deoplete-clang#3]
Go to include/declaration/definition

**Comment by zchee** [comment]
@butterflyfish Hi :)

This repository source for `deoplete.nvim`. so your implements are the burden is too heavy.

but, I planned `deoto.nvim`.
Dark powered Next Generation asynchronous Goto for Neovim.
Please wait for a little :)

**Comment by butterflyfish** [comment]
@zchee,thank you for your response. I'm looking forward your work.

**Comment by zchee** [comment]
@butterflyfish :)

**Comment by stfl** [comment]
Is there any progress on that?
Or any other recommendation to use?

Thanks

**Comment by zchee** [comment]
@stfl Current state...
https://github.com/zchee/clang-server
