### ISSUE TITLE
No completions, only error messages

### ISSUE THREAD

**Issue by Ploppz** [zchee/deoplete-clang#35]
## Problems summary

No completion, only error messages: https://bpaste.net/show/3765e65b4a9f

## Expected

Completion to work

## Environment Information

 - OS: Arch Linux
 - Neovim version: 0.1.4

## Provide a minimal init.vim with less than 50 lines and not plugin manager (Required!)

```vim
" ??
let g:deoplete#enable_at_startup = 1

syntax enable
filetype plugin indent on

" Test
let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1

" Files
set backup
set backupdir=~/.local/share/nvim/backup
set directory=~/.local/share/nvim/swap
set undofile
set undodir=~/.local/share/nvim/undo
" Basic configuration
set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4
set clipboard+=unnamedplus
set showcmd
set number
set scrolloff=15
set hlsearch
set cursorline
set nocompatible
set esckeys

" treat .c++ files as C++ source
autocmd BufNewFile, BufRead *.c++ setfiletype cpp
autocmd BufNewFile, BufRead *.t setfiletype cpp
autocmd BufNewFile, BufRead *.ino setfiletype cpp
autocmd BufNewFile,BufRead Tupfile,*.tup setf tup

autocmd! FileType c,cpp,java,php call CSyntaxAfter()
```

or, try use it [tests/deoplete-clang.vim](../tests/deoplete-clang.vim) --- which I also tried, in which I got these errors immediately when I started to type: https://bpaste.net/show/fcc0b34574b2

## The reproduce ways from neovim starting (Required!)

Edit a `.h` file.

## Generate a logfile if appropriate
With my normal `init.vim`: https://bpaste.net/show/abd9b84bc5b7 and https://bpaste.net/show/03529501ad81
With minimal `init.vim`: https://bpaste.net/show/c5c52e502719 and https://bpaste.net/show/71325c968ce4

## Screen shot (if possible)
Wouldn't really say a lot.

## Upload the log file
Dont' really know what to do here.

**Comment by Shougo** [comment]
```
clang.cindex.LibclangError: /opt/llvm/lib/libclang.dylib: cannot open shared object file: No such file or directory. To provide a path to libclang use Config.set_library_path() or Config.set_library_file().
```

libclang is already installed?
It seems not installed or wrong path.

**Comment by Ploppz** [comment]
`/opt/llvm` doesn't exist.
I have `clang` installed from official Arch repo. Just now I tried installing `lib32-clang`. Still doesn't work. This is the [log](https://bpaste.net/show/6386f260cda2), using the minimal `init.vim`. However, that error doesn't seem to happen with my normal `init.vim` file?
