### ISSUE TITLE
Completing from standard libraries

### ISSUE THREAD

**Issue by llwu** [zchee/deoplete-clang#36]
I'm just starting to use this plugin and I like it so far. I have a question: if I open a new file and start typing something like `#include <stdio.h>`, the `include` keyword will autocomplete but the `stdio.h` will not autocomplete. And words like `printf` will not autocomplete. Is such feature implemented? It is not important to me but I ask because I heard people mentioned such feature for deoplete and I wanted to know if it is supposed to work.

A minimal `init.vim` ([directly from the deoplete-clang repository](https://github.com/zchee/deoplete-clang/blob/master/tests/deoplete-clang.vim)) that shows what I mean:
```
" Tiny init.vim for deoplete-clang
set runtimepath+=.vim/bundle/deoplete.nvim
set runtimepath+=.vim/bundle/deoplete-clang

let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_smart_case = 1
let g:deoplete#file#enable_buffer_path = 1

let g:deoplete#sources#clang#libclang_path = "/usr/local/lib/libclang.dylib"
let g:deoplete#sources#clang#clang_header = '/usr/local/lib/clang'
" let g:deoplete#sources#clang#sort_algo = 'priority' " alphabetical

filetype plugin indent on
syntax on
```

* My `clang` is from `brew install llvm --with-clang` (OS X) or `emerge clang` (Gentoo)

Minimal example of code that I am typing:

```
#include <stdio.h>

int main() {
    printf("Hello World!\n");
    return 0;
}
```

While typing the above, only `include`, `int`, and `return` autocomplete. If this is correct/expected then I can close this issue.

**Comment by Shougo** [comment]
dup of #34
