### ISSUE TITLE
Per-project configuration?

### ISSUE THREAD

**Issue by TheAifam5** [zchee/deoplete-clang#46]
## Problems summary
Actually i don't see any documentations about per project configuration, which is a little bit annoying.

## Expected
Per project configuration file in JSON which be a lot of easier to edit than Python script. Actually I'm using YouComplete me but when i installed deoplete-clang i was a little bit shocked why doesnt have that.

## Environment Information

 - OS: ArchLinux x64
 - Neovim version: 0.1.4

**Comment by HiPhish** [comment]
Seems to be implemented, but not documented: #24
