### ISSUE TITLE
Snippets Support

### ISSUE THREAD

**Issue by crondog** [zchee/deoplete-clang#5]
It would be great to have snippet support for function arguments etc.

If I have time ill try to implement it

**Comment by zchee** [comment]
@crondog Hi :)
I do not understand all.

Can you give an example?

**Comment by Shougo** [comment]
If deoplete-clang provides the arguments information in abbr or info, neosippets already supported the feature.

**Comment by crondog** [comment]
Ok so it seems I was wrong. The placeholders are put in

**Comment by zchee** [comment]
@Shougo Thanks for advice :)
