### ISSUE TITLE
deoplete-clang opens new buffer on autocomplete

### ISSUE THREAD

**Issue by nickaleks** [zchee/deoplete-clang#55]
## Problems summary
Every time i use autocomplete from clang, a new buffer opens at the top, containing contents of the autocomplete. Is this the desired behavior?

## Environment Information

 - OS: Arch Linux
 - Neovim version: 0.1.5

## Provide a minimal init.vim with less than 50 lines and not plugin manager (Required!)

```vim
" start deoplete
let g:deoplete#enable_at_startup = 1
" remap autocomplete on tab
inoremap <silent><expr> <Tab> pumvisible() ? "\<C-n>" : deoplete#mappings#manual_complete()

" clang-deoplete configuration
let g:deoplete#sources#clang#libclang_path = "/usr/lib/libclang.so"
let g:deoplete#sources#clang#clang_header = "/usr/lib/clang/3.8.1/include"
```

This is fresh install, so this is basically whole init.vim. I tried to remove inoremap line, but even with default hotkeys this still happens

## The reproduce ways from neovim starting (Required!)

 1. Start typing.
 2. Select one of the clang autocomplete offers.
 3. It will create a new buffer at the top, with autocomplete test.

**Comment by nickaleks** [comment]
Update: found a hot fix by adding:
```vim
autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif
```
It closes the buffer after complete is done, however I would want buffer not to be opened at all, as it is quite disturbing.

**Comment by Shougo** [comment]
`set completeopt -=preview`
