### ISSUE TITLE
Could not load source: deoplete_clang

### ISSUE THREAD

**Issue by FireAntJoe** [zchee/deoplete-clang#56]
## Problems summary
As soon as I open up nvim I get this weird error messages 

## Expected
I expected no message and for this to work

## Environment Information

 - OS: Antergros latest 64bit
 - Neovim version: Latest 64bit

## Provide a minimal init.vim with less than 50 lines and not plugin manager (Required!)

call plug#end()

autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

set number

syntax enable
colorscheme monokai

" Use deoplete.

let g:deoplete#enable_at_startup = 1

let g:deoplete#sources#clang#libclang_path = '/usr/lib/libclang.so '

let g:deoplete#sources#clang#clang_header = '/usr/include/clang/'
or, try use it [tests/deoplete-clang.vim](../tests/deoplete-clang.vim)

## The reproduce ways from neovim starting (Required!)

1. Open up neovim with deoplete clang installed
* I installed python-libclang from yaourt earlier

## Generate a logfile if appropriate

1. Set environment variables for neovim Python remote plugin

        export NVIM_PYTHON_LOG_FILE=/tmp/log
        export NVIM_PYTHON_LOG_LEVEL=DEBUG

2. Run nvim

        nvim -u minimal.vimrc

3. some works
3. cat /tmp/log_{PID}

## Screen shot (if possible)
https://s9.postimg.org/52n0rpqwf/Screenshot_from_2016_09_08_12_09_17.png

## Upload the log file
 - `NVIM_PYTHON_LOG_FILE`
 - `$HOME`/.nvimlog

**Comment by Shougo** [comment]
"libclang" seems not installed.

Because, "/usr/lib/libclang.so" is not found error from your screenshot.
It is not deoplete-clang problem.

**Comment by zchee** [comment]
We talked in mail, close.
