### ISSUE TITLE
request: Adding CUDA filetype support

### ISSUE THREAD

**Issue by sunbubble** [zchee/deoplete-clang#60]
For the last couple of versions, clang is able to compile CUDA code. CUDA is it's own filetype but is essentially an extension of c++. So adding support to deoplete-clang shouldn't be complicated, however I wasn't able to do it. Could you please elaborate on what would be necessary.

http://llvm.org/docs/CompileCudaWithLLVM.html

**Comment by Shougo** [comment]
I will check it later.

**Comment by chibby0ne** [comment]
I don't think the support is completely implemented yet. Yes deoplete-clang identifies '.cu' filetype as cuda but autocompletion is not available.

**Comment by Shougo** [comment]
Hm.  In the first, clang completion does support CUDA?

**Comment by Shougo** [comment]
I cannot fix the problem.  Because, I don't have CUDA environment.
Pull request is wellcome.
