### ISSUE TITLE
could not working on Cmake and project-specified settings

### ISSUE THREAD

**Issue by dangkhoasdc** [zchee/deoplete-clang#61]
issue: could not working on Cmake and project-specified settings
I faced an annoying problem when trying to configure CMAKE and deoplete_clang. Here is my settings of deoplete and deoplete_clang:

```
             let g:deoplete#enable_at_startup = 1
            let g:deoplete#sources#clang#libclang_path = '/usr/lib/libclang.so'
            let g:deoplete#sources#clang#clang_header = '/usr/lib/clang/'
```

It works out-of-the-box, except integrating with CMAKE.

Here is my toy example.

![](https://d2mxuefqeaa7sj.cloudfront.net/s_D1CFE368B06E029C56302219C8FEE9EF1FE4899B860EFA74E2A5E79AE8DF0375_1477557426546_list_dir_2.png)

and CMakeLists.txt:

```
    cmake_minimum_required(VERSION 3.0)
    project(TestVIM)

    include_directories(include)
    set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
    add_executable(tri  src/main_tri.cpp)
    add_executable(rect  src/rect.cpp)
```

.clang:

```
compilation_database = /home/dangkhoa/Code/test-cpp/build/
```

deoplete-clang works well on `main_tri.cpp` and `rect.cpp` 

when I try to create a new header file, ex `circle.hpp` in `include` folder, the problem encounters:

![](https://d2mxuefqeaa7sj.cloudfront.net/s_D1CFE368B06E029C56302219C8FEE9EF1FE4899B860EFA74E2A5E79AE8DF0375_1477557622010_error.png)

The same error also appear when I create a new `cpp` file in `src` .

**Comment by Shougo** [comment]
I think `compilation_commands.json` is not generated in `compilation_database` directory.

**Comment by dangkhoasdc** [comment]
@Shougo Actually it did. The screenshot is taken before I ran `cmake ...`. `deoplete_clang` works well on existing `cpp` and `hpp` files. The problem only encounters when I create a new file.

**Comment by Shougo** [comment]
I think you must re-generate compilation_commands.json after new files are created.
It seems clang feature.

**Comment by Shougo** [comment]
I don't know this error can be fixed by deoplete-clang.

@zchee Ping.

**Comment by zchee** [comment]
@dangkhoasdc @Shougo Sorry for delay, I'll try debug it.

**Comment by Shougo** [comment]
It is bug.  I have fixed the error.
