### ISSUE TITLE
Can Deoplete Handle Function Parameter Completion?

### ISSUE THREAD

**Issue by sittim** [zchee/deoplete-clang#64]
This is just a question, but can deoplete do function parameter completion.  I think I saw somewhere that it can use neosnippet plug-in to auto-complete function parameters, is that true?

**Comment by Shougo** [comment]
It is neosnippet feature.
`:help g:neosnippet#enable_completed_snippet`

**Comment by zchee** [comment]
@Shougo Thanks support.

**Comment by sittim** [comment]
OK, but this is rather hidden, I think that adding little info to the README would make this an even more awesome package...
