### ISSUE TITLE
Auto detect clang header file paths

### ISSUE THREAD

**Issue by yshui** [zchee/deoplete-clang#73]
Everytime I update clang I need to update the header path in my init.nvim, which is annoying.

Is there a way to auto detect?

**Comment by Shougo** [comment]
https://github.com/zchee/deoplete-clang/issues/9

It can be implemented, but I think it is better to use deoplete-clang2 instead.
https://github.com/tweekmonster/deoplete-clang2

**Comment by yshui** [comment]
I didn't know that exists... So is deoplete-clang deprecated?

**Comment by zchee** [comment]
@yshui Sorry, Now I'm developing the https://github.com/zchee/clang-server
It's alternative C/C++ parser.
I planned to change the deoplete-clang libclang parser to clang-server.

But currently, https://github.com/tweekmonster/deoplete-clang2 is a good choice for completion of C/C++.
