### ISSUE TITLE
Completion too slow

### ISSUE THREAD

**Issue by StevenChenSE** [zchee/deoplete-clang#74]
## Problems summary
I switched to deoplete clang a couple of weeks ago. I think the feature that it offers both semantic and omni completion is real nice and it's far better than youcompleteme.

The only problem it has is that the completion is too slow, it will take 3-5 seconds for the completion list to pop up after I did some typing, I fully understand that it takes time for the clang engine to recompile after a change, but would the following enhancement be possible?

After typing some characters, deoplete first pop up some omni completion and snippets suggestions and do clang compiling in the background, once it's finished and then insert them to the top of the completion list.

**Comment by Shougo** [comment]
You should use deoplete-clang2 instead.
Unfortunately, deoplete-clang is very slow currently.
https://github.com/tweekmonster/deoplete-clang2

> After typing some characters, deoplete first pop up some omni completion and snippets suggestions and do clang compiling in the background, once it's finished and then insert them to the top of the completion list.

It is on the todo list.
https://github.com/Shougo/deoplete.nvim/issues/407
But I must refactor the implementation before that.
