### ISSUE TITLE
Deoplete-clang doesn't load : 'no module named deoplete.sources'

### ISSUE THREAD

**Issue by Edhebi** [zchee/deoplete-clang#77]
## Problems summary

I'm trying to setup a lightweight c++ dev environement, and deoplete-clan looks like a must-go for c++ autocompletion. The problem is, it doesn't want to load in nvim.

When launching vim from default shell, it fails to load whit the following message :
> [deoplete]   File "/home/leo/.local/share/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/
deoplete.py", line 342, in load_sources
> [deoplete]     Source = import_plugin(path, 'source', 'Source')
> [deoplete]   File "/home/leo/.local/share/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/
util.py", line 91, in import_plugin
> [deoplete]     module = SourceFileLoader(module_name, path).load_module()
> [deoplete]   File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
> [deoplete]   File "<frozen importlib._bootstrap_external>", line 823, in load_module
> [deoplete]   File "<frozen importlib._bootstrap_external>", line 682, in load_module
> [deoplete]   File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
> [deoplete]   File "<frozen importlib._bootstrap>", line 684, in _load
> [deoplete]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
> [deoplete]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
> [deoplete]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
> [deoplete]   File "/home/leo/.local/share/nvim/plugged/deoplete-clang/rplugin/python3/deoplete
/sources/deoplete_clang.py", line 4, in <module>
> [deoplete]     from deoplete.sources.base import Base
> [deoplete] ModuleNotFoundError: No module named 'deoplete.sources'
> [deoplete] Could not load source: deoplete_clang.  Use :messages for error details.

## Expected
adding deoplete.nvim and deoplete-clang to runtimepath, and it works

## Environment Information

 - OS: Ubuntu MATE 17.10 64bit
I know this is an experimental version, and if downgrading is the only fix, I will think about it
 - Neovim version: v0.2.0 (RelWithDebInfo)

## init.vim
```vim
set runtimepath+=~/.local/share/nvim/plugged/deoplete.nvim/
set runtimepath+=~/.local/share/nvim/plugged/deoplete-clang/

let g:deoplete#enable_at_startup = 1
```

## reproducing

 1. add deoplete.nvim and deoplete-clang to runtimepath through init.vim
 2. start nvim
 
## Logfile
[log_py3_rplugin.txt](https://github.com/zchee/deoplete-clang/files/1378665/log_py3_rplugin.txt)

**Comment by Shougo** [comment]
Your deoplete-clang seems not latest version.
Please install the latest version.

**Comment by Shougo** [comment]
>  from deoplete.sources.base import Base

Please read the souce code.
deoplete_clang.py has not the line.

**Comment by Edhebi** [comment]
Looks like vim-plugwas drunk, and I forgot to properly clean that plugged dir
-- closed for being a non issue --
