### ISSUE TITLE
CompilationDatabaseError exception

### ISSUE THREAD

**Issue by LKlemens** [zchee/deoplete-clang#80]
## Problems summary
I have problem with load compile_commnads.json. 
In :messages are some exceptions.
Code completion does not work.

## Some info about my cpp project.
My compile_commands.json is huge ~ 300k lines (~300 lines per file).
One file could compiling for 5 second with command:
```clang-check file -p . ```
but when I add ```--analyze``` flag file could compiling for 1.5 minute.

## Expected
Load compile_command.json and awesome async code completion should works.

## Environment Information

 - OS: Red Hat Enterprise Linux Server release 6.5
 - Neovim version: NVIM v0.2.3-564-g6452831

## Provide a minimal init.vim with less than 50 lines and not plugin manager (Required!)

```vim
" Your minimal init.vim
let g:deoplete#enable_at_startup = 1
let deoplete#tag#cache_limit_size = 5000000
let g:python_host_prog = '/usr/bin/python2'
let g:python3_host_prog = '/opt/python/x86_64/3.6.0/bin-wrapped/python'

" deoplete clang
let g:deoplete#enable_smart_case = 1
let g:deoplete#file#enable_buffer_path = 1
let g:deoplete#sources#clang#libclang_path = '/opt/llvm/x86_64/3.4-5/lib/libclang.so'
let g:deoplete#sources#clang#clang_header = '/opt/llvm/x86_64/3.4-5/lib/clang'
let g:deoplete#sources#clang#clang_complete_database= '/var/users/user/trunk'


```

## The reproduce ways from neovim starting (Required!)

 1. Open nvim with code
 2. In :messages are exceptions from deoplete clang

## Upload the log file
[py3_rplugin.txt](https://github.com/zchee/deoplete-clang/files/1738146/py3_rplugin.txt)
[messages.txt](https://github.com/zchee/deoplete-clang/files/1736747/messages.txt)

**Comment by LKlemens** [comment]
Hi, anyway some hints how to debug this issue will be very helpful too ;)

**Comment by Shougo** [comment]
deoplete-jedi is not maintained well.
Sorry.

**Comment by LKlemens** [comment]
@Shougo, @zchee  I appreciate your effort you put into open source. Thank you a lot guys! :)
If you would have some spare time, then any suggestion what/where I could check, and how I could debug that issue will be very helpful.
Thanks in advance.

**Comment by Shougo** [comment]
> My compile_commands.json is huge ~ 300k lines (~300 lines per file).
> One file could compiling for 5 second with command:
> clang-check file -p .
> but when I add --analyze flag file could compiling for 1.5 minute.

We cannot support the huge database.
You should reduce the size.
Sorry.

**Comment by Shougo** [comment]
> Load compile_command.json and awesome async code completion should works.

No magic.

**Comment by LKlemens** [comment]
I've reduced compile_commands.json to one file and issue still appearing. There is no way to cache results like in deoplete-jedi? 
I use ALE (Asynchronous Lint Engine) with that big compile_commands.json and it is works.
I do not want annoying you, I only want find out solution, but I am afraid I will not do it alone ;/

**Comment by Shougo** [comment]
deoplete-clang depends clang version.
Because it uses clangd.

**Comment by Shougo** [comment]
I am considering new deoplete source for clang...

C/C++ support is the weakpoint of deoplete.

**Comment by LKlemens** [comment]
> I am considering new deoplete source for clang...

Awesome! Tell me if I could somehow help you ;)

**Comment by LKlemens** [comment]
For others who will be struggling with big cpp projects ... 
https://github.com/rzaluska/deoplete-rtags with rtags server seems works well :P

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete-clangx

Here.
This is the test version.
