### ISSUE TITLE
how to enable this for arduino files?

### ISSUE THREAD

**Issue by clawoflight** [zchee/deoplete-clang#82]
I want to enable this source for arduino files.
I have an appropriate `.clang` file in my project folder and this line in my init.vim:

`let g:deoplete#sources.arduino = ['clang']`

But it doesn't work. What should I do?

**Comment by Shougo** [comment]
`arduino` is filetype name?

**Comment by clawoflight** [comment]
yes, `arduino` is ft. File ending is `.ino`.

**Comment by Shougo** [comment]
```vim
call deoplete#custom#source('clang', 'fileytpes', ['c', 'cpp', 'arduino'])
```
