### ISSUE TITLE
i cannot install on my windows laptop

### ISSUE THREAD

**Issue by vando2108** [zchee/deoplete-clang#96]
![image](https://user-images.githubusercontent.com/35914996/121782756-56394b00-cbd5-11eb-95ba-369fc17137f4.png)
![image](https://user-images.githubusercontent.com/35914996/121782775-69e4b180-cbd5-11eb-8033-bd1cd152a9d7.png)
Pls help me

**Comment by Shougo** [comment]
Please use `'` instead of `"` in `g:deoplete#sources#clang#libclang_path`.
Or please use `/` instead of `\` in `deoplete#sources#clang#libclang_path`.

Double quotes is not same with single quotes!
No magic.
